var huxVL = ["This no longer has purpose.",
"No longer useful.",
"Calculated destruction.",
"Perfect destruction.",
"Better now",
"This is better.",
"Obstacle removed.",
"Out of my way!",
"Terrible construction!",
"Weak and inferior!",
"Secured.",
"Genetic matter secured.",
"Genes secured.",
"Materials secured.",
"Matter secured.",
"Genetic material ready for transport.",
"Genes... useable.",
"Gene integrity. 78%.",
"Gene integrity. 43%.",
"Gene integrity. 96%.",
"Squirm little worm.",
"You should thank me for this.",
"Such a sad lower form of existence.",
"Grovel, grovel, little worm.",
"All things will succumb to my design.",
"It will all be over soon.",
"Yes. It hurts. Growth often does.",
"Prepare for transcedence.",
"Growth often hurts.",
"Your genes are limited.",
"Your genes need minor modifications.",
"You will fit my design.",
"Your genes need minor alterations.",
"You humans are so pathetic.",
"Prepare to become something better.",
"Stop squabbling you infinitesimal worm.",
"You are about to be made perfect.",
"I'm about to elevate your worth.",
"Stop blabbering. It's really annoying.",
"You are one annoying little worm.",
"You will be elevated to something more.",
"Something great is about to happen.",
"Die. Fast. Please.",
"It will be fast. Possibly painless.",
"It's over.",
"Vision down.",
"Vision compromised.",
"Reduced visibility. Recalibrating...",
"Partial darkness. Fixing cortex.",
"Analysing vision.",
"I can't see. Vision down.",
"Can't see. Vision compromised.",
"Surprising for an inferior lifeform.",
"You'll suffer more for that!",
"This is not possible!",
"You shouldn't do such things."];

function getRandomIntInclusive(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1) + min);
};

var nHux = getRandomIntInclusive(0, huxVL.length);

alert(huxVL[nHux]);
